### ISSUE TITLE
Dynamic Proxy restart

### ISSUE THREAD

**Issue by rikuge** [aivarsk/scrapy-proxies#25]
Is it possible to restart the proxylist if it gets to 0? I have dynamic proxies that refresh every 15 min, so I want scrapy to restart the list if len(self.proxies) == 0.

Thanks!

**Comment by ruehri** [comment]
Quick and dirty: Just call __init__ method if len(self.proxies) == 0
(You can also create a method which looks quite similar to __init__ and call that one instead)
